print("salam everyone")
print("my name is arooj")
print('mei ne course start kia hei ai engineering ke name se')
print('or aj seekha ke print command kia hein or double walay strings hotay hei or single quotes walay bhi')
print("This is a string using double quotes.")
print('This is a string using single quotes.')
print('or abhi test kr rhi hon command ko')
print("Python is my first programming language.")
print('I can use single quotes too.')
print("My goal is to become an AI Engineer.")
print('thankyou')